name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        pip install flake8

    - name: Análisis estático (flake8)
      run: |
        flake8 .

    - name: Ejecutar script (prueba básica)
      run: |
        python main.py
